-- Chat table 

CREATE TABLE chat (
  chat_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY AUTO_INCREMENT
)

-- User table 

CREATE TABLE "user" (
  user_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY AUTO_INCREMENT,
    chat_id INTEGER REFERENCES chat(chat_id),
  username VARCHAR(50) ,
  first_name VARCHAR(50),
  last_name VARCHAR(50),
  bio TEXT,
  last_seen TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
)

--  Messages table

CREATE TABLE messages (
  message_id SERIAL PRIMARY KEY AUTO_INCREMENT,
  receiver_chat_id INTEGER REFERENCES chat(chat_id),
  sender_user_id INTEGER REFERENCES "user"(user_id),
    send_time TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
)
--channel
create table channel(
  channel_id PRIMARY KEY AUTO_INCREMENT
name varchar(50)
  bio text
	--owner
	 FOREIGN KEY (user_id) REFERENCES user(user_id)
)
--group
create table group(
  group_id PRIMARY KEY AUTO_INCREMENT
name varchar(50)
  bio text
	--owner
	 FOREIGN KEY (user_id) REFERENCES user(user_id)
)
--admin/member
create table membergroup(
	primary key (user_id,group_id)
)
create table admingroup(
	primary key (user_id,group_id)
)
create table memberchannel(
	primary key (user_id,channel_id)
)
create table adminchannel(
	primary key (user_id,channel_id)
)
